### ISSUE TITLE
Suboptimal route calculation

### ISSUE THREAD

**Issue by wcraigtrader** [Auzzy/1846-routes-web#73] opened 2019-07-31 05:41 UTC
I was playing around with the route calculator, and setup the following situation:

**Tiles**
```
B16; 6; 2
D18; 8; 0
E19; 8; 3
E17; 296; 1
E15; 25; 4
D14; 619; 5
C13; 7; 5
D20; 14; 4
D12; 9; 1
D10; 9; 4
D8; 24; 4
D6; 298; 0
C15; 294; 0
E7; 7; 3
G19; 14; 2
F18; 9; 2
G7; 619; 4
G9; 619; 1
H10; 8; 2
I9; 8; 5
F6; 9; 2
E5; 8; 5
H6; 9; 3
J4; 8; 2
I3; 8; 1
F14; 8; 3
F12; 8; 0
G11; 8; 3
```

**Railroads**
```
Baltimore & Ohio; 3 / 5; G19, E17; 
Grand Trunk; 2, 3 / 5; B16, D14; 
New York Central; 2, 2, 2, 2; D20, E17, D6, C15; E7
Illinois Central; 2, 2, 3 / 5; K3, G9; 
Erie; ; E21; 
Chesapeake & Ohio; removed
Pennsylvania; removed
```

**Stations**
```
Steamboat Company; Baltimore & Ohio; G19
Meat Packing Company; ; 
Mail Contract; ; 
Big 4; Illinois Central; G9
Michigan Southern; New York Central; C15
```

When I asked for a calculation for Grand Trunk, I got this:
```
2: D14, C15 = 80
3 / 5: B16, C15, C13, D14, E15, E17 = 130
```

I think the better answer would have been:
```
2: D14, C15 = 80
3 / 5: C5, D6, D8, D10, D12, D14, C13, C15, C17 = 170
```

As I was writing this up, it did provide the better answer. Further testing indicates that if I calculate any other railroad, then GT, then I get the better answer. If I calculate GT again, I get the lesser answer. Subsequent calculations for GT provide the lesser answer, until I calculate another railroad.

**Comment by Auzzy** [comment] 2019-07-31 23:29
@wcraigtrader Thanks for the report! I'm digging in now. 

Also, for the future, it may be easier to click the "Report Issue" button in the top-right of the page. It will automatically send me the board, railroads, and private companies, and if you're on the tab with a route calculation, the results.

**Comment by Auzzy** [comment] 2019-08-01 05:21
I've tracked down the cause. There were 2 issues: incorrect hashing of routes, and incomplete subroute lists. I've got some more testing to do, so I'll look to deploy the change tomorrow evening, after some more testing. I'll go into more depth about what was wrong at that time, too.

**Comment by Auzzy** [comment] 2019-08-01 13:03
The fix has been deployed and tested.

There were 2 bugs which mixed to usually produce the right answer, but not always.

The first one involved removing duplicate routes, which were almost always the same in reverse (e.g. from above, C5 -> C17 and C17 -> C5). The problem is the way I was storing the coordinates was not sorted, and was not even deterministic. So the routes marked as duplicate were not stable across different runs.

Later on, when confirming the route crosses Chicago legally (Chicago is a PITA), I look for the section of the route that goes from Chicago Connections, to Chicago, to one of Chicago's neighbors. However, due to a bug in gathering this section, the starting cell of the route mattered (e.g. C5 or C17). When it was C5, it was fine, but when it was C17, it looked like there was no path to Chicago Connections.

**Closed by Auzzy** 2019-08-01 13:03 UTC
Labels: bug, in progress
